---
global:
  scrape_interval: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: telegraf
  static_configs:
  - targets:
    - telegraf:9273
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
...
