{
 "title": "Main",
 "tags": [ "selenoid" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpjson_selenoid_status_used{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpjson_selenoid_status_queued{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpjson_selenoid_status_pending{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total containers usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (browser) (label_replace({__name__=~\"httpjson_selenoid_status_browsers_.*\"}, \"browser\", \"$1\", \"__name__\", \".*browsers_(.*)_.*_count\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (id,name)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (id,name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage / Selenoid Containers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_browser=~\".+\"}[1m])) by (id,image) * 100",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Memory Usage / Selenoid Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_label_browser=~\".+\"}) by (id,image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (id,name) * 100",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) * 100",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{name=~\".+\"}) by (id,name)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum (container_memory_usage_bytes{name=~\".+\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\".+\",name=~\".+\"})/60",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}